# Generated by Django 3.2.16 on 2023-02-21 16:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('alloylookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alloy',
            managers=[
                ('alloy_object_list', django.db.models.manager.Manager()),
            ],
        ),
    ]
