# Generated by Django 4.1.5 on 2023-01-30 16:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloylookup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloy',
            name='elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('si_min', 'Si Min'), ('si_max', 'Si Max')], max_length=10, null=True), blank=True, null=True, size=None),
        ),
    ]
