# Generated by Django 3.2.16 on 2023-03-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alloylookup', '0002_alter_country_country_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footnote_id', models.IntegerField(unique=True)),
                ('footnote', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='alloy',
            name='primary_footnote_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_footnote_id', to='alloylookup.footnote'),
        ),
        migrations.AlterField(
            model_name='alloy',
            name='secondary_footnote_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_footnote_id', to='alloylookup.footnote'),
        ),
        migrations.DeleteModel(
            name='PrimaryFootnote',
        ),
        migrations.DeleteModel(
            name='SecondaryFootnote',
        ),
    ]
