# Generated by Django 3.2.16 on 2023-02-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloylookup', '0002_auto_20230203_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloy',
            name='alloy_elements',
            field=models.JSONField(default='dict'),
        ),
    ]
