# Generated by Django 3.2.16 on 2023-01-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alloylookup', '0002_alloy_elements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alloy',
            name='elements',
        ),
    ]
