# Generated by Django 3.2.16 on 2023-02-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alloylookup', '0002_alter_alloy_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alloy',
            managers=[
            ],
        ),
    ]
