# Generated by Django 3.2.16 on 2023-03-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alloylookup', '0002_auto_20230310_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alloyelement',
            old_name='alloy',
            new_name='alloy_code',
        ),
    ]
