# Generated by Django 4.1.5 on 2023-01-18 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alloylookup', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlloyDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloy_code', models.IntegerField()),
                ('alloy_description', models.CharField(max_length=300)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alloylookup.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alloylookup.subcategory')),
            ],
        ),
    ]
