# Generated by Django 3.2.16 on 2023-03-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloylookup', '0004_rename_alloy_code_alloyelement_alloy'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloy',
            name='alloy_elements',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='AlloyElement',
        ),
    ]
