# Generated by Django 3.2.16 on 2023-02-05 12:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloylookup', '0006_alter_alloy_alloy_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloy',
            name='alloy_elements_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=[], size=None),
        ),
    ]
