# Generated by Django 3.2.16 on 2023-02-05 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloylookup', '0007_alloy_alloy_elements_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloy',
            name='alloy_elements_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=dict, size=None),
        ),
    ]
